matrix:
  include:
    - language: android
      components:
        # Use the latest SDK Platform Tools ("tools" is intentionally listed twice
        # following the Travis CI docs)
        - tools
        - platform-tools
        - tools
        # buildToolsVersion
        - build-tools-27.0.3
        # compileSdkVersion
        - android-27
        - extra-android-m2repository
        - extra-android-support
        - extra-google-google_play_services
        - extra-google-m2repository
        - add-on
        - extra
      
      before_install:
        - nvm install 10

      install:
        - npm install --global expo-cli
      
      script:
        - expo eject --non-interactive --eject-method expoKit
        - ./gradlew assembleProdMinSdkProdKernel

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
