matrix:
  include:
    - language: android
      android:
        components:
          # Use the latest SDK Platform Tools ("tools" is intentionally listed twice
          # following the Travis CI docs)
          - tools
          - platform-tools
          - tools

          # buildToolsVersion
          - build-tools-27.0.3

          # compileSdkVersion
          - android-27

          - extra-android-m2repository
          - extra-android-support
          - extra-google-google_play_services
          - extra-google-m2repository
      
      before_install:
        - nvm install 10

      install:
        - npm install --global expo-cli
        - npm install
      
      before_script:
        - expo login --non-interactive --username "$EXPO_USERNAME" --password "$EXPO_PASSWORD"

      script:
        # Detach the project
        - expo eject --non-interactive --eject-method expoKit
        - sudo ln -s "$(which expo)" /usr/local/bin/exp

        # Publish the project
        - expo publish --non-interactive

        # Build the APK
        - cd android
        - ./gradlew assembleProdMinSdkProdKernelRelease
        - cd "$TRAVIS_BUILD_DIR"
        - cp android/app/build/outputs/apk/prodMinSdkProdKernel/release/app-prodMinSdk-prodKernel-release-unsigned.apk "app-release-unsigned-build-${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.apk"
      
      addons:
        artifacts:
          s3_region: "us-west-2"
          paths:
            - "app-release-unsigned-build-${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.apk"
          target_paths: 
            - builds

      before_cache:
        - npm cache verify
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.npm/
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
